x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./deploy/nanobot:/root/.nanobot

services:
  mihomo:
    container_name: nanobot-proxy
    image: ghcr.io/metacubex/mihomo:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./deploy/proxy/mihomo:/etc/mihomo
    ports:
      - 18790:18790
      - 7890:7890
      - 9090:9090

  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    network_mode: service:mihomo
    depends_on:
      - mihomo
    command: ["gateway"]

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    network_mode: service:mihomo
    depends_on:
      - mihomo
    command: ["status"]
    stdin_open: true
    tty: true
